apiVersion: apps/v1
kind: Deployment
metadata:
  name: trans-deployment
  labels:
    app: trans-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trans-app
  template:
    metadata:
      labels:
        app: trans-app
    spec:
      containers:
      - name: trans-app
        image: tang2432/ml-assignment:v1
        ports:
        - containerPort: 9527
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: trans-service
spec:
  type: NodePort
  selector:
      app: trans-app
  ports:
    - protocol: TCP
      port: 9527
      targetPort: 9527
